apiVersion: batch/v1
kind: Job
metadata:
  name: run-tests-job-${PELTON_RUN}
spec:
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        test-job: sb-optimistic-entities
    spec:
      restartPolicy: Never
      containers:
      - name: run-tests-ctnr-${PELTON_RUN}
        image: ${PELTON_BRES}
        args: $PELTON_TARGET_ARGS